In [1]:
# Created by Xu An on 2018/10/19.
# Copyright © 2018 Xu An. All rights reserved.

# Homework: Ch03 Edge & Node

### 有一4阶张量`img`其`shape=[10, 28, 28, 3])`，代表10张28*28像素的3通道RGB图像，问：

In [5]:
import tensorflow as tf
import numpy as np

img = tf.random_uniform([10,28,28,3])

sess = tf.Session()
print(sess.run(img))

[[[[1.94705009e-01 6.69538736e-01 6.73449278e-01]
   [9.61859941e-01 6.46002173e-01 7.02305794e-01]
   [6.03300691e-01 9.88632917e-01 6.12918258e-01]
   ...
   [5.50417185e-01 3.34269285e-01 3.85245681e-01]
   [9.98330355e-01 2.81012774e-01 3.53441954e-01]
   [2.72934914e-01 3.54753017e-01 8.40709209e-01]]

  [[7.30154634e-01 5.09209871e-01 7.30225444e-01]
   [2.40852475e-01 3.67316008e-01 6.45651221e-01]
   [6.26370668e-01 6.72806978e-01 7.57995844e-02]
   ...
   [1.09788060e-01 3.87829542e-02 4.78668094e-01]
   [2.63614297e-01 1.41100526e-01 9.77044463e-01]
   [1.77067399e-01 5.91944575e-01 4.24985647e-01]]

  [[1.87201619e-01 3.83141041e-01 4.91535544e-01]
   [3.51860523e-01 5.65632582e-02 6.63011312e-01]
   [1.49105787e-02 5.80821037e-02 4.90982652e-01]
   ...
   [5.12732863e-01 3.72859240e-01 9.62425709e-01]
   [4.66589928e-02 9.06446934e-01 4.32809591e-02]
   [1.99691176e-01 1.05030894e-01 2.55771875e-02]]

  ...

  [[5.61896324e-01 7.64292717e-01 3.28102231e-01]
   [1.59007311e-

#### 1. 如何利用索引取出第2张图片？（注意：索引均从0开始，第二张则索引为1，下同）

In [36]:
img2 = img[1]

img2.shape

TensorShape([Dimension(28), Dimension(28), Dimension(3)])

#### 2. 如何利用切片取出第2张图片？

In [37]:
img2_1 = tf.slice(img,[1,0,0,0],[1,28,28,3])

img2_1.shape

TensorShape([Dimension(1), Dimension(28), Dimension(28), Dimension(3)])

#### 3. 使用切片与使用索引取出的一张图片有何不同？

区别：使用索引得到的图片的rank为3,但是使用切片得到的shape与原始数据保持一致，均为4

#### 4. 如何取出其中的第1、3、5、7张图片？

In [34]:
img_odd = img[0:8:2]

img_odd.shape

TensorShape([Dimension(4), Dimension(28), Dimension(28), Dimension(3)])

#### 5. 如何取出第6-8张（包括6不包括8）图片中中心区域（14*14）的部分？

In [41]:
img_cen = img[6:8,7:21,7:21]

img_cen.shape

TensorShape([Dimension(2), Dimension(14), Dimension(14), Dimension(3)])

#### 6. 如何将图片根据通道拆分成三份单通道图片？

In [55]:
path1 = tf.slice(img,[0,0,0,0],[10,28,28,1])

path2 = tf.slice(img,[0,0,0,1],[10,28,28,2])

path3 = tf.slice(img,[0,0,0,2],[10,28,28,3])

print(path1.shape)
print(path2.shape)
print(path3.shape)

(10, 28, 28, 1)
(10, 28, 28, 2)
(10, 28, 28, 3)


#### 7.写出`tf.shape(img)`返回的张量的阶数以及`shape`属性的值。

In [67]:
shape = tf.shape(img)

rank = tf.rank(shape) # rank is 1

sess = tf.Session()
print(sess.run(rank))

sess = tf.Session()  # result is [10 28 28 3]
print(sess.run(shape))

1
[10 28 28  3]
